name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: src/cdk
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Set cdk.json
      run: |
        # jq --arg AMPLIFY_OAUTH_TOKEN "$AMPLIFY_OAUTH_TOKEN" '.context.prod.env.amplifyOauthToken = $AMPLIFY_OAUTH_TOKEN' .cdk.json > tmp.json
        # mv cdk.json tmp.json
        # jq --arg API_ENDPOINT "$API_ENDPOINT" '.context.prod.env.apiEndpoint = $API_ENDPOINT' tmp.json > cdk.json
        mv .cdk.json cdk.json

    - name: Build and deploy
      run: |
        npm run build
        cdk deploy -c environment=prod --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
